// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: client/commands.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommandType defines all possible command types
type CommandType int32

const (
	CommandType_UNKNOWN CommandType = 0
	// DEPLOY
	CommandType_DEPLOY   CommandType = 1
	CommandType_UNDEPLOY CommandType = 2
	// BOOTSTRAP
	CommandType_UPDATE_BOOTSTRAP CommandType = 11
	// SERVICES
	CommandType_SERVICE CommandType = 21
	// CLIENT
	CommandType_CLIENT_LOGS  CommandType = 31
	CommandType_CLIENT_STATS CommandType = 32
	// PROXY
	CommandType_PROXY CommandType = 41
	// NETWORK
	CommandType_NETWORK CommandType = 51
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "DEPLOY",
		2:  "UNDEPLOY",
		11: "UPDATE_BOOTSTRAP",
		21: "SERVICE",
		31: "CLIENT_LOGS",
		32: "CLIENT_STATS",
		41: "PROXY",
		51: "NETWORK",
	}
	CommandType_value = map[string]int32{
		"UNKNOWN":          0,
		"DEPLOY":           1,
		"UNDEPLOY":         2,
		"UPDATE_BOOTSTRAP": 11,
		"SERVICE":          21,
		"CLIENT_LOGS":      31,
		"CLIENT_STATS":     32,
		"PROXY":            41,
		"NETWORK":          51,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_client_commands_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_client_commands_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_client_commands_proto_rawDescGZIP(), []int{0}
}

var File_client_commands_proto protoreflect.FileDescriptor

var file_client_commands_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2a,
	0x92, 0x01, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x44, 0x45, 0x50, 0x4c, 0x4f, 0x59, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x55, 0x4e, 0x44, 0x45,
	0x50, 0x4c, 0x4f, 0x59, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45,
	0x5f, 0x42, 0x4f, 0x4f, 0x54, 0x53, 0x54, 0x52, 0x41, 0x50, 0x10, 0x0b, 0x12, 0x0b, 0x0a, 0x07,
	0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x10, 0x15, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4c, 0x49,
	0x45, 0x4e, 0x54, 0x5f, 0x4c, 0x4f, 0x47, 0x53, 0x10, 0x1f, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x4c,
	0x49, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x53, 0x10, 0x20, 0x12, 0x09, 0x0a, 0x05,
	0x50, 0x52, 0x4f, 0x58, 0x59, 0x10, 0x29, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x45, 0x54, 0x57, 0x4f,
	0x52, 0x4b, 0x10, 0x33, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x45, 0x6c, 0x63, 0x68, 0x69, 0x54, 0x68, 0x65, 0x47, 0x72, 0x65, 0x61, 0x74,
	0x2f, 0x65, 0x6c, 0x63, 0x68, 0x69, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_client_commands_proto_rawDescOnce sync.Once
	file_client_commands_proto_rawDescData = file_client_commands_proto_rawDesc
)

func file_client_commands_proto_rawDescGZIP() []byte {
	file_client_commands_proto_rawDescOnce.Do(func() {
		file_client_commands_proto_rawDescData = protoimpl.X.CompressGZIP(file_client_commands_proto_rawDescData)
	})
	return file_client_commands_proto_rawDescData
}

var file_client_commands_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_client_commands_proto_goTypes = []any{
	(CommandType)(0), // 0: client.CommandType
}
var file_client_commands_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_client_commands_proto_init() }
func file_client_commands_proto_init() {
	if File_client_commands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_client_commands_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_commands_proto_goTypes,
		DependencyIndexes: file_client_commands_proto_depIdxs,
		EnumInfos:         file_client_commands_proto_enumTypes,
	}.Build()
	File_client_commands_proto = out.File
	file_client_commands_proto_rawDesc = nil
	file_client_commands_proto_goTypes = nil
	file_client_commands_proto_depIdxs = nil
}
