// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: client/request.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Deploy related messages
type RequestDeploy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ipv4      string `protobuf:"bytes,2,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Port      uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Version   string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Bootstrap []byte `protobuf:"bytes,5,opt,name=bootstrap,proto3" json:"bootstrap,omitempty"`
}

func (x *RequestDeploy) Reset() {
	*x = RequestDeploy{}
	mi := &file_client_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDeploy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDeploy) ProtoMessage() {}

func (x *RequestDeploy) ProtoReflect() protoreflect.Message {
	mi := &file_client_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDeploy.ProtoReflect.Descriptor instead.
func (*RequestDeploy) Descriptor() ([]byte, []int) {
	return file_client_request_proto_rawDescGZIP(), []int{0}
}

func (x *RequestDeploy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestDeploy) GetIpv4() string {
	if x != nil {
		return x.Ipv4
	}
	return ""
}

func (x *RequestDeploy) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RequestDeploy) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RequestDeploy) GetBootstrap() []byte {
	if x != nil {
		return x.Bootstrap
	}
	return nil
}

type RequestUnDeploy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *RequestUnDeploy) Reset() {
	*x = RequestUnDeploy{}
	mi := &file_client_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUnDeploy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUnDeploy) ProtoMessage() {}

func (x *RequestUnDeploy) ProtoReflect() protoreflect.Message {
	mi := &file_client_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUnDeploy.ProtoReflect.Descriptor instead.
func (*RequestUnDeploy) Descriptor() ([]byte, []int) {
	return file_client_request_proto_rawDescGZIP(), []int{1}
}

func (x *RequestUnDeploy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestUnDeploy) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type RequestService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port  uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Count uint32 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *RequestService) Reset() {
	*x = RequestService{}
	mi := &file_client_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestService) ProtoMessage() {}

func (x *RequestService) ProtoReflect() protoreflect.Message {
	mi := &file_client_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestService.ProtoReflect.Descriptor instead.
func (*RequestService) Descriptor() ([]byte, []int) {
	return file_client_request_proto_rawDescGZIP(), []int{2}
}

func (x *RequestService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestService) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RequestService) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RequestUpdateBootstrap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port      uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Bootstrap []byte `protobuf:"bytes,3,opt,name=bootstrap,proto3" json:"bootstrap,omitempty"`
}

func (x *RequestUpdateBootstrap) Reset() {
	*x = RequestUpdateBootstrap{}
	mi := &file_client_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUpdateBootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUpdateBootstrap) ProtoMessage() {}

func (x *RequestUpdateBootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_client_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUpdateBootstrap.ProtoReflect.Descriptor instead.
func (*RequestUpdateBootstrap) Descriptor() ([]byte, []int) {
	return file_client_request_proto_rawDescGZIP(), []int{3}
}

func (x *RequestUpdateBootstrap) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestUpdateBootstrap) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RequestUpdateBootstrap) GetBootstrap() []byte {
	if x != nil {
		return x.Bootstrap
	}
	return nil
}

type RequestEnvoyAdmin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port   uint32            `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Method string            `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Path   string            `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Query  map[string]string `protobuf:"bytes,5,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body   string            `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *RequestEnvoyAdmin) Reset() {
	*x = RequestEnvoyAdmin{}
	mi := &file_client_request_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEnvoyAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEnvoyAdmin) ProtoMessage() {}

func (x *RequestEnvoyAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_client_request_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEnvoyAdmin.ProtoReflect.Descriptor instead.
func (*RequestEnvoyAdmin) Descriptor() ([]byte, []int) {
	return file_client_request_proto_rawDescGZIP(), []int{4}
}

func (x *RequestEnvoyAdmin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestEnvoyAdmin) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RequestEnvoyAdmin) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestEnvoyAdmin) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RequestEnvoyAdmin) GetQuery() map[string]string {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *RequestEnvoyAdmin) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_client_request_proto protoreflect.FileDescriptor

var file_client_request_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x83,
	0x01, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x70, 0x76, 0x34, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x69, 0x70, 0x76, 0x34, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74,
	0x72, 0x61, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x74, 0x73,
	0x74, 0x72, 0x61, 0x70, 0x22, 0x39, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x55,
	0x6e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22,
	0x4e, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x5e, 0x0a, 0x16, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x22,
	0xf1, 0x01, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x76, 0x6f, 0x79,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x3a, 0x0a, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x76, 0x6f, 0x79, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x1a, 0x38, 0x0a, 0x0a, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x45, 0x6c, 0x63, 0x68, 0x69, 0x54, 0x68, 0x65, 0x47, 0x72, 0x65, 0x61, 0x74, 0x2f,
	0x62, 0x69, 0x67, 0x62, 0x61, 0x6e, 0x67, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_client_request_proto_rawDescOnce sync.Once
	file_client_request_proto_rawDescData = file_client_request_proto_rawDesc
)

func file_client_request_proto_rawDescGZIP() []byte {
	file_client_request_proto_rawDescOnce.Do(func() {
		file_client_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_client_request_proto_rawDescData)
	})
	return file_client_request_proto_rawDescData
}

var file_client_request_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_client_request_proto_goTypes = []any{
	(*RequestDeploy)(nil),          // 0: client.RequestDeploy
	(*RequestUnDeploy)(nil),        // 1: client.RequestUnDeploy
	(*RequestService)(nil),         // 2: client.RequestService
	(*RequestUpdateBootstrap)(nil), // 3: client.RequestUpdateBootstrap
	(*RequestEnvoyAdmin)(nil),      // 4: client.RequestEnvoyAdmin
	nil,                            // 5: client.RequestEnvoyAdmin.QueryEntry
}
var file_client_request_proto_depIdxs = []int32{
	5, // 0: client.RequestEnvoyAdmin.query:type_name -> client.RequestEnvoyAdmin.QueryEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_client_request_proto_init() }
func file_client_request_proto_init() {
	if File_client_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_client_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_request_proto_goTypes,
		DependencyIndexes: file_client_request_proto_depIdxs,
		MessageInfos:      file_client_request_proto_msgTypes,
	}.Build()
	File_client_request_proto = out.File
	file_client_request_proto_rawDesc = nil
	file_client_request_proto_goTypes = nil
	file_client_request_proto_depIdxs = nil
}
