// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: client/response.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseDeploy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files             string `protobuf:"bytes,1,opt,name=files,proto3" json:"files,omitempty"`
	Service           string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Network           string `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	DownstreamAddress string `protobuf:"bytes,4,opt,name=downstream_address,json=downstreamAddress,proto3" json:"downstream_address,omitempty"`
	Port              uint32 `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *ResponseDeploy) Reset() {
	*x = ResponseDeploy{}
	mi := &file_client_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseDeploy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDeploy) ProtoMessage() {}

func (x *ResponseDeploy) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDeploy.ProtoReflect.Descriptor instead.
func (*ResponseDeploy) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseDeploy) GetFiles() string {
	if x != nil {
		return x.Files
	}
	return ""
}

func (x *ResponseDeploy) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ResponseDeploy) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ResponseDeploy) GetDownstreamAddress() string {
	if x != nil {
		return x.DownstreamAddress
	}
	return ""
}

func (x *ResponseDeploy) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type ResponseUnDeploy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files             string `protobuf:"bytes,1,opt,name=files,proto3" json:"files,omitempty"`
	Service           string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Network           string `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	DownstreamAddress string `protobuf:"bytes,4,opt,name=downstream_address,json=downstreamAddress,proto3" json:"downstream_address,omitempty"`
	Port              uint32 `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *ResponseUnDeploy) Reset() {
	*x = ResponseUnDeploy{}
	mi := &file_client_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseUnDeploy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUnDeploy) ProtoMessage() {}

func (x *ResponseUnDeploy) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUnDeploy.ProtoReflect.Descriptor instead.
func (*ResponseUnDeploy) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseUnDeploy) GetFiles() string {
	if x != nil {
		return x.Files
	}
	return ""
}

func (x *ResponseUnDeploy) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ResponseUnDeploy) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ResponseUnDeploy) GetDownstreamAddress() string {
	if x != nil {
		return x.DownstreamAddress
	}
	return ""
}

func (x *ResponseUnDeploy) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type ResponseUpdateBootstrap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ResponseUpdateBootstrap) Reset() {
	*x = ResponseUpdateBootstrap{}
	mi := &file_client_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseUpdateBootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUpdateBootstrap) ProtoMessage() {}

func (x *ResponseUpdateBootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUpdateBootstrap.ProtoReflect.Descriptor instead.
func (*ResponseUpdateBootstrap) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseUpdateBootstrap) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ResponseService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status *ServiceStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Logs   []*Logs        `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
}

func (x *ResponseService) Reset() {
	*x = ResponseService{}
	mi := &file_client_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseService) ProtoMessage() {}

func (x *ResponseService) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseService.ProtoReflect.Descriptor instead.
func (*ResponseService) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseService) GetStatus() *ServiceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ResponseService) GetLogs() []*Logs {
	if x != nil {
		return x.Logs
	}
	return nil
}

type ServiceStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Loaded  string   `protobuf:"bytes,1,opt,name=loaded,proto3" json:"loaded,omitempty"`
	Active  string   `protobuf:"bytes,2,opt,name=active,proto3" json:"active,omitempty"`
	MainPid string   `protobuf:"bytes,3,opt,name=main_pid,json=mainPid,proto3" json:"main_pid,omitempty"`
	Tasks   string   `protobuf:"bytes,4,opt,name=tasks,proto3" json:"tasks,omitempty"`
	Memory  string   `protobuf:"bytes,5,opt,name=memory,proto3" json:"memory,omitempty"`
	Cpu     string   `protobuf:"bytes,6,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Cgroup  []string `protobuf:"bytes,7,rep,name=cgroup,proto3" json:"cgroup,omitempty"`
}

func (x *ServiceStatus) Reset() {
	*x = ServiceStatus{}
	mi := &file_client_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatus) ProtoMessage() {}

func (x *ServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatus.ProtoReflect.Descriptor instead.
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceStatus) GetLoaded() string {
	if x != nil {
		return x.Loaded
	}
	return ""
}

func (x *ServiceStatus) GetActive() string {
	if x != nil {
		return x.Active
	}
	return ""
}

func (x *ServiceStatus) GetMainPid() string {
	if x != nil {
		return x.MainPid
	}
	return ""
}

func (x *ServiceStatus) GetTasks() string {
	if x != nil {
		return x.Tasks
	}
	return ""
}

func (x *ServiceStatus) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *ServiceStatus) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *ServiceStatus) GetCgroup() []string {
	if x != nil {
		return x.Cgroup
	}
	return nil
}

type Logs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message   string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Level     string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Component string `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	Timestamp string `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *Logs) Reset() {
	*x = Logs{}
	mi := &file_client_response_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logs) ProtoMessage() {}

func (x *Logs) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logs.ProtoReflect.Descriptor instead.
func (*Logs) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{5}
}

func (x *Logs) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Logs) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Logs) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *Logs) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type ResponseEnvoyAdmin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32             `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Body       string            `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Headers    map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ResponseEnvoyAdmin) Reset() {
	*x = ResponseEnvoyAdmin{}
	mi := &file_client_response_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseEnvoyAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseEnvoyAdmin) ProtoMessage() {}

func (x *ResponseEnvoyAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseEnvoyAdmin.ProtoReflect.Descriptor instead.
func (*ResponseEnvoyAdmin) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{6}
}

func (x *ResponseEnvoyAdmin) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ResponseEnvoyAdmin) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ResponseEnvoyAdmin) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

var File_client_response_proto protoreflect.FileDescriptor

var file_client_response_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22,
	0x9d, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x2d, 0x0a, 0x12,
	0x64, 0x6f, 0x77, 0x6e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x64, 0x6f, 0x77, 0x6e, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22,
	0x9f, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55, 0x6e, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x2d,
	0x0a, 0x12, 0x64, 0x6f, 0x77, 0x6e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x64, 0x6f, 0x77, 0x6e,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x22, 0x2d, 0x0a, 0x17, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x76, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x6f,
	0x67, 0x73, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x22, 0xb2, 0x01, 0x0a, 0x0d, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f,
	0x61, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x6f, 0x61, 0x64,
	0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61,
	0x69, 0x6e, 0x5f, 0x70, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61,
	0x69, 0x6e, 0x50, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x63, 0x70, 0x75, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18,
	0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x63, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x72, 0x0a,
	0x04, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e,
	0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x22, 0xc8, 0x01, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x6e,
	0x76, 0x6f, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x41, 0x0a,
	0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x45, 0x6e, 0x76, 0x6f, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73,
	0x1a, 0x3a, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x2d, 0x5a, 0x2b,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x45, 0x6c, 0x63, 0x68, 0x69,
	0x54, 0x68, 0x65, 0x47, 0x72, 0x65, 0x61, 0x74, 0x2f, 0x65, 0x6c, 0x63, 0x68, 0x69, 0x2d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_client_response_proto_rawDescOnce sync.Once
	file_client_response_proto_rawDescData = file_client_response_proto_rawDesc
)

func file_client_response_proto_rawDescGZIP() []byte {
	file_client_response_proto_rawDescOnce.Do(func() {
		file_client_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_client_response_proto_rawDescData)
	})
	return file_client_response_proto_rawDescData
}

var file_client_response_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_client_response_proto_goTypes = []any{
	(*ResponseDeploy)(nil),          // 0: client.ResponseDeploy
	(*ResponseUnDeploy)(nil),        // 1: client.ResponseUnDeploy
	(*ResponseUpdateBootstrap)(nil), // 2: client.ResponseUpdateBootstrap
	(*ResponseService)(nil),         // 3: client.ResponseService
	(*ServiceStatus)(nil),           // 4: client.ServiceStatus
	(*Logs)(nil),                    // 5: client.Logs
	(*ResponseEnvoyAdmin)(nil),      // 6: client.ResponseEnvoyAdmin
	nil,                             // 7: client.ResponseEnvoyAdmin.HeadersEntry
}
var file_client_response_proto_depIdxs = []int32{
	4, // 0: client.ResponseService.status:type_name -> client.ServiceStatus
	5, // 1: client.ResponseService.logs:type_name -> client.Logs
	7, // 2: client.ResponseEnvoyAdmin.headers:type_name -> client.ResponseEnvoyAdmin.HeadersEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_client_response_proto_init() }
func file_client_response_proto_init() {
	if File_client_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_client_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_response_proto_goTypes,
		DependencyIndexes: file_client_response_proto_depIdxs,
		MessageInfos:      file_client_response_proto_msgTypes,
	}.Build()
	File_client_response_proto = out.File
	file_client_response_proto_rawDesc = nil
	file_client_response_proto_goTypes = nil
	file_client_response_proto_depIdxs = nil
}
