// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: client/response.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseDeploy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files   string `protobuf:"bytes,1,opt,name=files,proto3" json:"files,omitempty"`
	Service string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Network string `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
}

func (x *ResponseDeploy) Reset() {
	*x = ResponseDeploy{}
	mi := &file_client_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseDeploy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDeploy) ProtoMessage() {}

func (x *ResponseDeploy) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDeploy.ProtoReflect.Descriptor instead.
func (*ResponseDeploy) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseDeploy) GetFiles() string {
	if x != nil {
		return x.Files
	}
	return ""
}

func (x *ResponseDeploy) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ResponseDeploy) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type ResponseService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cmdline string         `protobuf:"bytes,2,opt,name=cmdline,proto3" json:"cmdline,omitempty"`
	Logs    []*ServiceLogs `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
}

func (x *ResponseService) Reset() {
	*x = ResponseService{}
	mi := &file_client_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseService) ProtoMessage() {}

func (x *ResponseService) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseService.ProtoReflect.Descriptor instead.
func (*ResponseService) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseService) GetCmdline() string {
	if x != nil {
		return x.Cmdline
	}
	return ""
}

func (x *ResponseService) GetLogs() []*ServiceLogs {
	if x != nil {
		return x.Logs
	}
	return nil
}

type ServiceLogs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message   string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Level     string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Component string `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	Timestamp string `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Cmdline   string `protobuf:"bytes,5,opt,name=cmdline,proto3" json:"cmdline,omitempty"`
	Unit      string `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	Host      string `protobuf:"bytes,7,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *ServiceLogs) Reset() {
	*x = ServiceLogs{}
	mi := &file_client_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceLogs) ProtoMessage() {}

func (x *ServiceLogs) ProtoReflect() protoreflect.Message {
	mi := &file_client_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceLogs.ProtoReflect.Descriptor instead.
func (*ServiceLogs) Descriptor() ([]byte, []int) {
	return file_client_response_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceLogs) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServiceLogs) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *ServiceLogs) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *ServiceLogs) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ServiceLogs) GetCmdline() string {
	if x != nil {
		return x.Cmdline
	}
	return ""
}

func (x *ServiceLogs) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ServiceLogs) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

var File_client_response_proto protoreflect.FileDescriptor

var file_client_response_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22,
	0x5a, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0x68, 0x0a, 0x0f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6d, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6d, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x27, 0x0a, 0x04,
	0x6c, 0x6f, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x6f, 0x67, 0x73, 0x52,
	0x04, 0x6c, 0x6f, 0x67, 0x73, 0x22, 0xbb, 0x01, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e,
	0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6d, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6d, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x6e, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68,
	0x6f, 0x73, 0x74, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x45, 0x6c, 0x63, 0x68, 0x69, 0x54, 0x68, 0x65, 0x47, 0x72, 0x65, 0x61, 0x74, 0x2f,
	0x62, 0x69, 0x67, 0x62, 0x61, 0x6e, 0x67, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_client_response_proto_rawDescOnce sync.Once
	file_client_response_proto_rawDescData = file_client_response_proto_rawDesc
)

func file_client_response_proto_rawDescGZIP() []byte {
	file_client_response_proto_rawDescOnce.Do(func() {
		file_client_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_client_response_proto_rawDescData)
	})
	return file_client_response_proto_rawDescData
}

var file_client_response_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_client_response_proto_goTypes = []any{
	(*ResponseDeploy)(nil),  // 0: client.ResponseDeploy
	(*ResponseService)(nil), // 1: client.ResponseService
	(*ServiceLogs)(nil),     // 2: client.ServiceLogs
}
var file_client_response_proto_depIdxs = []int32{
	2, // 0: client.ResponseService.logs:type_name -> client.ServiceLogs
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_client_response_proto_init() }
func file_client_response_proto_init() {
	if File_client_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_client_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_response_proto_goTypes,
		DependencyIndexes: file_client_response_proto_depIdxs,
		MessageInfos:      file_client_response_proto_msgTypes,
	}.Build()
	File_client_response_proto = out.File
	file_client_response_proto_rawDesc = nil
	file_client_response_proto_goTypes = nil
	file_client_response_proto_depIdxs = nil
}
